import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:intl/intl.dart';

import '../../core/constants/api_constants.dart';
import '../../core/utils/session_manager.dart';

/// A single planned task generated by AI (editable before confirming).
class PlannedTask {
  String title;
  DateTime dueDate; // IST
  String priority; // low, medium, high
  String notes;

  PlannedTask({
    required this.title,
    required this.dueDate,
    this.priority = 'medium',
    this.notes = '',
  });

  Map<String, dynamic> toJson() => {
        'title': title,
        'dueDate': dueDate.toUtc().toIso8601String(),
        'priority': priority,
        'notes': notes,
      };
}

class AIPlannerController extends ChangeNotifier {
  /// System timezone name for prompt context
  static final String _tzLabel = DateTime.now().timeZoneName;

  final String _apiKey = ApiConstants.geminiApiKey;
  final String _backendUrl = ApiConstants.backendUrl;

  // ── State ──
  bool isGenerating = false;
  String? errorMessage;
  List<PlannedTask> generatedTasks = [];
  bool isUploading = false;

  /// Existing tasks for context (fetched once per session).
  List<Map<String, dynamic>> _allTasks = [];
  String? _defaultListId;

  // ── Helpers ──
  DateTime nowLocal() => DateTime.now();

  String _formatLocal(DateTime dt) =>
      DateFormat("EEE, d MMM yyyy 'at' h:mm a").format(dt);

  /* ══════════════════════════════════════════════════════════════════
     FETCH TASKS + DEFAULT LIST
     ══════════════════════════════════════════════════════════════════ */

  Future<void> loadTasksAndLists() async {
    debugPrint('🔵 [AIPlannerCtrl] loadTasksAndLists() called');
    final token = await SessionManager.getToken();
    final userId = await SessionManager.getUserId();
    debugPrint('🔵 [AIPlannerCtrl] token=${token != null ? 'present' : 'NULL'}, userId=$userId');
    if (token == null || userId == null) {
      debugPrint('❌ [AIPlannerCtrl] token or userId is null, aborting load');
      return;
    }

    // Fetch tasks
    try {
      final taskRes = await http.get(
        Uri.parse('$_backendUrl/api/task/$userId'),
        headers: {'Authorization': 'Bearer $token'},
      );
      debugPrint('🔵 [AIPlannerCtrl] Fetch tasks status: ${taskRes.statusCode}');
      if (taskRes.statusCode == 200) {
        _allTasks =
            List<Map<String, dynamic>>.from(jsonDecode(taskRes.body)['data'] ?? []);
        debugPrint('🔵 [AIPlannerCtrl] Loaded ${_allTasks.length} tasks');
      } else {
        debugPrint('❌ [AIPlannerCtrl] Fetch tasks failed: ${taskRes.statusCode} - ${taskRes.body}');
      }
    } catch (e, st) {
      debugPrint('❌ [AIPlannerCtrl] Fetch tasks exception: $e\n$st');
    }

    // Fetch task lists → find default
    try {
      final listRes = await http.get(
        Uri.parse('$_backendUrl/api/taskList/$userId'),
        headers: {'Authorization': 'Bearer $token'},
      );
      debugPrint('🔵 [AIPlannerCtrl] Fetch lists status: ${listRes.statusCode}');
      if (listRes.statusCode == 200) {
        final lists =
            List<Map<String, dynamic>>.from(jsonDecode(listRes.body)['data'] ?? []);
        debugPrint('🔵 [AIPlannerCtrl] Loaded ${lists.length} task lists');
        final def = lists.firstWhere(
          (l) => l['isDefault'] == true,
          orElse: () => lists.isNotEmpty ? lists.first : <String, dynamic>{},
        );
        _defaultListId = def['_id']?.toString();
        debugPrint('🔵 [AIPlannerCtrl] Default list ID: $_defaultListId');
      } else {
        debugPrint('❌ [AIPlannerCtrl] Fetch lists failed: ${listRes.statusCode} - ${listRes.body}');
      }
    } catch (e, st) {
      debugPrint('❌ [AIPlannerCtrl] Fetch lists exception: $e\n$st');
    }
  }

  /* ══════════════════════════════════════════════════════════════════
     FILTER TASKS FOR A DATE / WEEK
     ══════════════════════════════════════════════════════════════════ */

  List<Map<String, dynamic>> tasksForDate(DateTime date) {
    final day = DateTime(date.year, date.month, date.day);
    return _allTasks.where((t) {
      if (t['isArchived'] == true) return false;
      final d = DateTime.tryParse(t['dueDate'] ?? '')?.toLocal();
      if (d == null) return false;
      return DateTime(d.year, d.month, d.day) == day;
    }).toList();
  }

  List<Map<String, dynamic>> tasksForWeek(DateTime startDate) {
    final start = DateTime(startDate.year, startDate.month, startDate.day);
    final end = start.add(const Duration(days: 7));
    return _allTasks.where((t) {
      if (t['isArchived'] == true) return false;
      final d = DateTime.tryParse(t['dueDate'] ?? '')?.toLocal();
      if (d == null) return false;
      final dd = DateTime(d.year, d.month, d.day);
      return !dd.isBefore(start) && dd.isBefore(end);
    }).toList();
  }

  String _taskContextFor(List<Map<String, dynamic>> tasks) {
    if (tasks.isEmpty) return 'No existing tasks.';
    return tasks.map((t) {
      final title = t['title'] ?? 'Untitled';
      final status = t['status'] ?? 'pending';
      final priority = t['priority'] ?? 'medium';
      final dueRaw = t['dueDate'];
      String due = 'No due date';
      if (dueRaw != null) {
        final d = DateTime.tryParse(dueRaw)?.toLocal();
        if (d != null) due = _formatLocal(d);
      }
      return '- [$status] $title | due: $due | priority: $priority';
    }).join('\n');
  }

  /* ══════════════════════════════════════════════════════════════════
     GENERATE DAY PLAN
     ══════════════════════════════════════════════════════════════════ */

  Future<void> generateDayPlan(DateTime date, String userPrompt) async {
    isGenerating = true;
    errorMessage = null;
    generatedTasks = [];
    notifyListeners();

    try {
      final existingTasks = tasksForDate(date);
      final ctx = _taskContextFor(existingTasks);
      final dateStr = DateFormat('EEEE, d MMM yyyy').format(date);
      final nowStr = _formatLocal(nowLocal());

      final prompt =
          "You are an AI day planner.\n\n"
          "CURRENT TIME ($_tzLabel): $nowStr\n"
          "PLANNING FOR: $dateStr\n\n"
          "EXISTING TASKS ON THIS DAY:\n$ctx\n\n"
          "USER'S REQUEST: $userPrompt\n\n"
          "RULES:\n"
          "1. Generate a smart day plan as a list of NEW tasks to add.\n"
          "2. DO NOT duplicate any existing tasks listed above.\n"
          "3. Each task must have a realistic time slot on $dateStr.\n"
          "4. Auto-assign priority (low/medium/high) based on importance.\n"
          "5. Return ONLY a JSON array of objects, no markdown, no explanation.\n"
          "   Each object: {\"title\": \"...\", \"time\": \"HH:mm\", \"priority\": \"...\", \"notes\": \"...\"}\n"
          "6. Keep titles short and actionable.\n"
          "7. Generate 4–8 tasks that make a productive day plan.\n"
          "8. Ensure times don't overlap and are in chronological order.\n";

      final result = await _callGemini(prompt);
      debugPrint('🟢 [AIPlannerCtrl]   Gemini result: ${result == null ? 'NULL' : '${result.length} chars'}');
      if (result == null) {
        debugPrint('❌ [AIPlannerCtrl]   AI returned null — service unavailable');
        errorMessage = 'AI service unavailable. Please try again.';
        isGenerating = false;
        notifyListeners();
        return;
      }
      debugPrint('🟢 [AIPlannerCtrl]   Raw AI response (first 500 chars): ${result.substring(0, result.length > 500 ? 500 : result.length)}');

      _parseTasks(result, date);
      debugPrint('🟢 [AIPlannerCtrl]   After parse: ${generatedTasks.length} tasks, error=$errorMessage');
    } catch (e, st) {
      debugPrint('❌ [AIPlannerCtrl]   generateDayPlan EXCEPTION: $e\n$st');
      errorMessage = 'Something went wrong. Please try again.';
    }

    isGenerating = false;
    notifyListeners();
  }

  /* ══════════════════════════════════════════════════════════════════
     GENERATE WEEK PLAN
     ══════════════════════════════════════════════════════════════════ */

  Future<void> generateWeekPlan(DateTime startDate, String userPrompt) async {
    debugPrint('🟣 [AIPlannerCtrl] generateWeekPlan() called');
    debugPrint('🟣 [AIPlannerCtrl]   startDate=$startDate, prompt="$userPrompt"');
    isGenerating = true;
    errorMessage = null;
    generatedTasks = [];
    notifyListeners();

    try {
      final existingTasks = tasksForWeek(startDate);
      debugPrint('🟣 [AIPlannerCtrl]   existing tasks for week: ${existingTasks.length}');
      final ctx = _taskContextFor(existingTasks);
      final startStr = DateFormat('EEEE, d MMM yyyy').format(startDate);
      final endDate = startDate.add(const Duration(days: 6));
      final endStr = DateFormat('EEEE, d MMM yyyy').format(endDate);
      final nowStr = _formatLocal(nowLocal());
      debugPrint('🟣 [AIPlannerCtrl]   week: $startStr → $endStr, now: $nowStr');

      final prompt =
          "You are an AI week planner.\n\n"
          "CURRENT TIME ($_tzLabel): $nowStr\n"
          "PLANNING WEEK: $startStr → $endStr (7 days)\n\n"
          "EXISTING TASKS THIS WEEK:\n$ctx\n\n"
          "USER'S REQUEST: $userPrompt\n\n"
          "RULES:\n"
          "1. Generate a comprehensive week plan as a list of NEW tasks.\n"
          "2. DO NOT duplicate any existing tasks listed above.\n"
          "3. Spread tasks across all 7 days sensibly.\n"
          "4. Each task must have a specific date and time.\n"
          "5. Auto-assign priority (low/medium/high).\n"
          "6. Return ONLY a JSON array of objects, no markdown, no explanation.\n"
          "   Each object: {\"title\": \"...\", \"date\": \"yyyy-MM-dd\", \"time\": \"HH:mm\", \"priority\": \"...\", \"notes\": \"...\"}\n"
          "7. Keep titles short and actionable.\n"
          "8. Generate 10–20 tasks for a productive week.\n"
          "9. Ensure no time overlaps within the same day.\n"
          "10. Sort by date then time.\n";

      final result = await _callGemini(prompt);
      debugPrint('🟣 [AIPlannerCtrl]   Gemini result: ${result == null ? 'NULL' : '${result.length} chars'}');
      if (result == null) {
        debugPrint('❌ [AIPlannerCtrl]   AI returned null — service unavailable');
        errorMessage = 'AI service unavailable. Please try again.';
        isGenerating = false;
        notifyListeners();
        return;
      }
      debugPrint('🟣 [AIPlannerCtrl]   Raw AI response (first 500 chars): ${result.substring(0, result.length > 500 ? 500 : result.length)}');

      _parseWeekTasks(result, startDate);
      debugPrint('🟣 [AIPlannerCtrl]   After parse: ${generatedTasks.length} tasks, error=$errorMessage');
    } catch (e, st) {
      debugPrint('❌ [AIPlannerCtrl]   generateWeekPlan EXCEPTION: $e\n$st');
      errorMessage = 'Something went wrong. Please try again.';
    }

    isGenerating = false;
    notifyListeners();
  }

  /* ══════════════════════════════════════════════════════════════════
     GEMINI CALL
     ══════════════════════════════════════════════════════════════════ */

  Future<String?> _callGemini(String prompt) async {
    debugPrint('🌐 [AIPlannerCtrl] _callGemini() sending request...');
    final uri = Uri.parse(
      'https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=$_apiKey',
    );

    try {
      final response = await http.post(
        uri,
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          'contents': [
            {
              'role': 'user',
              'parts': [
                {'text': prompt}
              ],
            }
          ],
          'generationConfig': {'temperature': 0.4, 'maxOutputTokens': 8192},
        }),
      );

      debugPrint('🌐 [AIPlannerCtrl] Gemini response status: ${response.statusCode}');
      if (response.statusCode != 200) {
        debugPrint('❌ [AIPlannerCtrl] Gemini error body: ${response.body}');
        return null;
      }

      final data = jsonDecode(response.body);
      final text = data['candidates']?[0]?['content']?['parts']?[0]?['text'] as String?;
      debugPrint('🌐 [AIPlannerCtrl] Gemini extracted text: ${text == null ? 'NULL' : '${text.length} chars'}');
      return text;
    } catch (e, st) {
      debugPrint('❌ [AIPlannerCtrl] _callGemini EXCEPTION: $e\n$st');
      return null;
    }
  }

  /* ══════════════════════════════════════════════════════════════════
     PARSE AI RESPONSE
     ══════════════════════════════════════════════════════════════════ */

  void _parseTasks(String raw, DateTime date) {
    try {
      // Strip markdown code fences (```json ... ```)
      String cleaned = raw.replaceAll(RegExp(r'```(?:json)?\s*', caseSensitive: false), '').trim();

      var jsonMatch = RegExp(r'\[.*\]', dotAll: true).firstMatch(cleaned);

      // Handle truncated JSON: find '[' but no closing ']'
      if (jsonMatch == null && cleaned.contains('[')) {
        final startIdx = cleaned.indexOf('[');
        String partial = cleaned.substring(startIdx);
        final lastBrace = partial.lastIndexOf('}');
        if (lastBrace > 0) {
          partial = '${partial.substring(0, lastBrace + 1)}]';
          jsonMatch = RegExp(r'\[.*\]', dotAll: true).firstMatch(partial);
        }
      }

      if (jsonMatch == null) {
        errorMessage = 'AI returned an unexpected format. Try again.';
        return;
      }
      final List items = jsonDecode(jsonMatch.group(0)!);
      generatedTasks = items.map((item) {
        final timeParts = (item['time'] as String? ?? '09:00').split(':');
        final hour = int.tryParse(timeParts[0]) ?? 9;
        final minute = timeParts.length > 1 ? (int.tryParse(timeParts[1]) ?? 0) : 0;
        return PlannedTask(
          title: item['title'] ?? 'Untitled',
          dueDate: DateTime(date.year, date.month, date.day, hour, minute),
          priority: item['priority'] ?? 'medium',
          notes: item['notes'] ?? '',
        );
      }).toList();
    } catch (_) {
      errorMessage = 'Failed to parse AI response. Try again.';
    }
  }

  void _parseWeekTasks(String raw, DateTime startDate) {
    debugPrint('🔧 [AIPlannerCtrl] _parseWeekTasks() called, raw length=${raw.length}');
    try {
      // Strip markdown code fences (```json ... ```)
      String cleaned = raw.replaceAll(RegExp(r'```(?:json)?\s*', caseSensitive: false), '').trim();
      debugPrint('🔧 [AIPlannerCtrl] After stripping fences: ${cleaned.length} chars');

      var jsonMatch = RegExp(r'\[.*\]', dotAll: true).firstMatch(cleaned);

      // Handle truncated JSON: if we find '[' but no closing ']'
      if (jsonMatch == null && cleaned.contains('[')) {
        debugPrint('🔧 [AIPlannerCtrl] No closing ] found — attempting truncation repair');
        final startIdx = cleaned.indexOf('[');
        String partial = cleaned.substring(startIdx);
        // Find the last complete object by locating the last '}'
        final lastBrace = partial.lastIndexOf('}');
        if (lastBrace > 0) {
          partial = '${partial.substring(0, lastBrace + 1)}]';
          debugPrint('🔧 [AIPlannerCtrl] Repaired JSON length: ${partial.length}');
          jsonMatch = RegExp(r'\[.*\]', dotAll: true).firstMatch(partial);
        }
      }

      if (jsonMatch == null) {
        debugPrint('❌ [AIPlannerCtrl] No JSON array found in AI response');
        debugPrint('❌ [AIPlannerCtrl] Raw response: $raw');
        errorMessage = 'AI returned an unexpected format. Try again.';
        return;
      }
      final jsonStr = jsonMatch.group(0)!;
      debugPrint('🔧 [AIPlannerCtrl] Extracted JSON length: ${jsonStr.length}');
      final List items = jsonDecode(jsonStr);
      debugPrint('🔧 [AIPlannerCtrl] Parsed ${items.length} items from JSON');
      generatedTasks = items.asMap().entries.map((entry) {
        final i = entry.key;
        final item = entry.value;
        debugPrint('🔧 [AIPlannerCtrl]   Item[$i]: $item');
        final dateStr = item['date'] as String? ??
            DateFormat('yyyy-MM-dd').format(startDate);
        final parsed = DateTime.tryParse(dateStr) ?? startDate;
        final timeParts = (item['time'] as String? ?? '09:00').split(':');
        final hour = int.tryParse(timeParts[0]) ?? 9;
        final minute = timeParts.length > 1 ? (int.tryParse(timeParts[1]) ?? 0) : 0;
        final dueDate = DateTime(parsed.year, parsed.month, parsed.day, hour, minute);
        debugPrint('🔧 [AIPlannerCtrl]   → title="${item['title']}", dueDate=$dueDate, priority=${item['priority']}');
        return PlannedTask(
          title: item['title'] ?? 'Untitled',
          dueDate: dueDate,
          priority: item['priority'] ?? 'medium',
          notes: item['notes'] ?? '',
        );
      }).toList();
      // Sort by date/time
      generatedTasks.sort((a, b) => a.dueDate.compareTo(b.dueDate));
      debugPrint('🔧 [AIPlannerCtrl] Final sorted tasks: ${generatedTasks.length}');
    } catch (e, st) {
      debugPrint('❌ [AIPlannerCtrl] _parseWeekTasks EXCEPTION: $e\n$st');
      debugPrint('❌ [AIPlannerCtrl] Raw was: $raw');
      errorMessage = 'Failed to parse AI response. Try again.';
    }
  }

  /* ══════════════════════════════════════════════════════════════════
     EDIT A PLANNED TASK
     ══════════════════════════════════════════════════════════════════ */

  void updateTask(int index, PlannedTask updated) {
    if (index >= 0 && index < generatedTasks.length) {
      generatedTasks[index] = updated;
      notifyListeners();
    }
  }

  void removeTask(int index) {
    if (index >= 0 && index < generatedTasks.length) {
      generatedTasks.removeAt(index);
      notifyListeners();
    }
  }

  /* ══════════════════════════════════════════════════════════════════
     CONFIRM & UPLOAD ALL TASKS TO BACKEND
     ══════════════════════════════════════════════════════════════════ */

  Future<bool> confirmAndUpload() async {
    debugPrint('🚀 [AIPlannerCtrl] confirmAndUpload() called');
    debugPrint('🚀 [AIPlannerCtrl]   tasks=${generatedTasks.length}, defaultListId=$_defaultListId');
    if (generatedTasks.isEmpty || _defaultListId == null) {
      debugPrint('❌ [AIPlannerCtrl] Aborting upload: tasks empty=${generatedTasks.isEmpty}, listId null=${_defaultListId == null}');
      return false;
    }

    isUploading = true;
    notifyListeners();

    final token = await SessionManager.getToken();
    final userId = await SessionManager.getUserId();
    if (token == null || userId == null) {
      debugPrint('❌ [AIPlannerCtrl] Aborting upload: token or userId null');
      isUploading = false;
      notifyListeners();
      return false;
    }

    int successCount = 0;
    for (int i = 0; i < generatedTasks.length; i++) {
      final task = generatedTasks[i];
      final payload = {
        'userId': userId,
        'taskListId': _defaultListId,
        'title': task.title,
        'notes': task.notes,
        'priority': task.priority,
        'dueDate': task.dueDate.toUtc().toIso8601String(),
        'status': 'pending',
        'isArchived': false,
        'reminder': {'enabled': false},
        'repeat': null,
      };

      debugPrint('🚀 [AIPlannerCtrl]   Uploading task[$i]: "${task.title}" due=${task.dueDate} → UTC=${task.dueDate.toUtc().toIso8601String()}');
      try {
        final res = await http.post(
          Uri.parse('$_backendUrl/api/task'),
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer $token',
          },
          body: jsonEncode(payload),
        );
        debugPrint('🚀 [AIPlannerCtrl]   Task[$i] upload status: ${res.statusCode}');
        if (res.statusCode == 200 || res.statusCode == 201) {
          successCount++;
        } else {
          debugPrint('❌ [AIPlannerCtrl]   Task[$i] upload failed: ${res.body}');
        }
      } catch (e, st) {
        debugPrint('❌ [AIPlannerCtrl]   Task[$i] upload EXCEPTION: $e\n$st');
      }
    }

    isUploading = false;
    final allOk = successCount == generatedTasks.length;
    debugPrint('🚀 [AIPlannerCtrl] Upload complete: $successCount/${generatedTasks.length} succeeded, allOk=$allOk');
    if (allOk) generatedTasks.clear();
    notifyListeners();
    return allOk;
  }

  void clearPlan() {
    generatedTasks.clear();
    errorMessage = null;
    notifyListeners();
  }
}
