import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:intl/intl.dart';

import '../../core/constants/api_constants.dart';
import '../../core/utils/session_manager.dart';

/// A single planned task generated by AI (editable before confirming).
class PlannedTask {
  String title;
  DateTime dueDate; // IST
  String priority; // low, medium, high
  String notes;

  PlannedTask({
    required this.title,
    required this.dueDate,
    this.priority = 'medium',
    this.notes = '',
  });

  Map<String, dynamic> toJson() => {
        'title': title,
        'dueDate': dueDate.toUtc().toIso8601String(),
        'priority': priority,
        'notes': notes,
      };
}

class AIPlannerController extends ChangeNotifier {
  /// System timezone name for prompt context
  static final String _tzLabel = DateTime.now().timeZoneName;

  final String _apiKey = ApiConstants.geminiApiKey;
  final String _backendUrl = ApiConstants.backendUrl;

  // ── State ──
  bool isGenerating = false;
  String? errorMessage;
  List<PlannedTask> generatedTasks = [];
  bool isUploading = false;

  /// Existing tasks for context (fetched once per session).
  List<Map<String, dynamic>> _allTasks = [];
  String? _defaultListId;

  // ── Helpers ──
  DateTime nowLocal() => DateTime.now();

  String _formatLocal(DateTime dt) =>
      DateFormat("EEE, d MMM yyyy 'at' h:mm a").format(dt);

  /* ══════════════════════════════════════════════════════════════════
     FETCH TASKS + DEFAULT LIST
     ══════════════════════════════════════════════════════════════════ */

  Future<void> loadTasksAndLists() async {
    final token = await SessionManager.getToken();
    final userId = await SessionManager.getUserId();
    if (token == null || userId == null) return;

    // Fetch tasks
    final taskRes = await http.get(
      Uri.parse('$_backendUrl/api/task/$userId'),
      headers: {'Authorization': 'Bearer $token'},
    );
    if (taskRes.statusCode == 200) {
      _allTasks =
          List<Map<String, dynamic>>.from(jsonDecode(taskRes.body)['data'] ?? []);
    }

    // Fetch task lists → find default
    final listRes = await http.get(
      Uri.parse('$_backendUrl/api/taskList/$userId'),
      headers: {'Authorization': 'Bearer $token'},
    );
    if (listRes.statusCode == 200) {
      final lists =
          List<Map<String, dynamic>>.from(jsonDecode(listRes.body)['data'] ?? []);
      final def = lists.firstWhere(
        (l) => l['isDefault'] == true,
        orElse: () => lists.isNotEmpty ? lists.first : <String, dynamic>{},
      );
      _defaultListId = def['_id']?.toString();
    }
  }

  /* ══════════════════════════════════════════════════════════════════
     FILTER TASKS FOR A DATE / WEEK
     ══════════════════════════════════════════════════════════════════ */

  List<Map<String, dynamic>> tasksForDate(DateTime date) {
    final day = DateTime(date.year, date.month, date.day);
    return _allTasks.where((t) {
      if (t['isArchived'] == true) return false;
      final d = DateTime.tryParse(t['dueDate'] ?? '')?.toLocal();
      if (d == null) return false;
      return DateTime(d.year, d.month, d.day) == day;
    }).toList();
  }

  List<Map<String, dynamic>> tasksForWeek(DateTime startDate) {
    final start = DateTime(startDate.year, startDate.month, startDate.day);
    final end = start.add(const Duration(days: 7));
    return _allTasks.where((t) {
      if (t['isArchived'] == true) return false;
      final d = DateTime.tryParse(t['dueDate'] ?? '')?.toLocal();
      if (d == null) return false;
      final dd = DateTime(d.year, d.month, d.day);
      return !dd.isBefore(start) && dd.isBefore(end);
    }).toList();
  }

  String _taskContextFor(List<Map<String, dynamic>> tasks) {
    if (tasks.isEmpty) return 'No existing tasks.';
    return tasks.map((t) {
      final title = t['title'] ?? 'Untitled';
      final status = t['status'] ?? 'pending';
      final priority = t['priority'] ?? 'medium';
      final dueRaw = t['dueDate'];
      String due = 'No due date';
      if (dueRaw != null) {
        final d = DateTime.tryParse(dueRaw)?.toLocal();
        if (d != null) due = _formatLocal(d);
      }
      return '- [$status] $title | due: $due | priority: $priority';
    }).join('\n');
  }

  /* ══════════════════════════════════════════════════════════════════
     GENERATE DAY PLAN
     ══════════════════════════════════════════════════════════════════ */

  Future<void> generateDayPlan(DateTime date, String userPrompt) async {
    isGenerating = true;
    errorMessage = null;
    generatedTasks = [];
    notifyListeners();

    try {
      final existingTasks = tasksForDate(date);
      final ctx = _taskContextFor(existingTasks);
      final dateStr = DateFormat('EEEE, d MMM yyyy').format(date);
      final nowStr = _formatLocal(nowLocal());

      final prompt =
          "You are an AI day planner.\n\n"
          "CURRENT TIME ($_tzLabel): $nowStr\n"
          "PLANNING FOR: $dateStr\n\n"
          "EXISTING TASKS ON THIS DAY:\n$ctx\n\n"
          "USER'S REQUEST: $userPrompt\n\n"
          "RULES:\n"
          "1. Generate a smart day plan as a list of NEW tasks to add.\n"
          "2. DO NOT duplicate any existing tasks listed above.\n"
          "3. Each task must have a realistic time slot on $dateStr.\n"
          "4. Auto-assign priority (low/medium/high) based on importance.\n"
          "5. Return ONLY a JSON array of objects, no markdown, no explanation.\n"
          "   Each object: {\"title\": \"...\", \"time\": \"HH:mm\", \"priority\": \"...\", \"notes\": \"...\"}\n"
          "6. Keep titles short and actionable.\n"
          "7. Generate 4–8 tasks that make a productive day plan.\n"
          "8. Ensure times don't overlap and are in chronological order.\n";

      final result = await _callGemini(prompt);
      if (result == null) {
        errorMessage = 'AI service unavailable. Please try again.';
        isGenerating = false;
        notifyListeners();
        return;
      }

      _parseTasks(result, date);
    } catch (e) {
      errorMessage = 'Something went wrong. Please try again.';
    }

    isGenerating = false;
    notifyListeners();
  }

  /* ══════════════════════════════════════════════════════════════════
     GENERATE WEEK PLAN
     ══════════════════════════════════════════════════════════════════ */

  Future<void> generateWeekPlan(DateTime startDate, String userPrompt) async {
    isGenerating = true;
    errorMessage = null;
    generatedTasks = [];
    notifyListeners();

    try {
      final existingTasks = tasksForWeek(startDate);
      final ctx = _taskContextFor(existingTasks);
      final startStr = DateFormat('EEEE, d MMM yyyy').format(startDate);
      final endDate = startDate.add(const Duration(days: 6));
      final endStr = DateFormat('EEEE, d MMM yyyy').format(endDate);
      final nowStr = _formatLocal(nowLocal());

      final prompt =
          "You are an AI week planner.\n\n"
          "CURRENT TIME ($_tzLabel): $nowStr\n"
          "PLANNING WEEK: $startStr → $endStr (7 days)\n\n"
          "EXISTING TASKS THIS WEEK:\n$ctx\n\n"
          "USER'S REQUEST: $userPrompt\n\n"
          "RULES:\n"
          "1. Generate a comprehensive week plan as a list of NEW tasks.\n"
          "2. DO NOT duplicate any existing tasks listed above.\n"
          "3. Spread tasks across all 7 days sensibly.\n"
          "4. Each task must have a specific date and time.\n"
          "5. Auto-assign priority (low/medium/high).\n"
          "6. Return ONLY a JSON array of objects, no markdown, no explanation.\n"
          "   Each object: {\"title\": \"...\", \"date\": \"yyyy-MM-dd\", \"time\": \"HH:mm\", \"priority\": \"...\", \"notes\": \"...\"}\n"
          "7. Keep titles short and actionable.\n"
          "8. Generate 10–20 tasks for a productive week.\n"
          "9. Ensure no time overlaps within the same day.\n"
          "10. Sort by date then time.\n";

      final result = await _callGemini(prompt);
      if (result == null) {
        errorMessage = 'AI service unavailable. Please try again.';
        isGenerating = false;
        notifyListeners();
        return;
      }

      _parseWeekTasks(result, startDate);
    } catch (e) {
      errorMessage = 'Something went wrong. Please try again.';
    }

    isGenerating = false;
    notifyListeners();
  }

  /* ══════════════════════════════════════════════════════════════════
     GEMINI CALL
     ══════════════════════════════════════════════════════════════════ */

  Future<String?> _callGemini(String prompt) async {
    final uri = Uri.parse(
      'https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=$_apiKey',
    );

    final response = await http.post(
      uri,
      headers: {'Content-Type': 'application/json'},
      body: jsonEncode({
        'contents': [
          {
            'role': 'user',
            'parts': [
              {'text': prompt}
            ],
          }
        ],
        'generationConfig': {'temperature': 0.4, 'maxOutputTokens': 2048},
      }),
    );

    if (response.statusCode != 200) return null;

    final data = jsonDecode(response.body);
    return data['candidates']?[0]?['content']?['parts']?[0]?['text'] as String?;
  }

  /* ══════════════════════════════════════════════════════════════════
     PARSE AI RESPONSE
     ══════════════════════════════════════════════════════════════════ */

  void _parseTasks(String raw, DateTime date) {
    try {
      final jsonMatch = RegExp(r'\[.*\]', dotAll: true).firstMatch(raw);
      if (jsonMatch == null) {
        errorMessage = 'AI returned an unexpected format. Try again.';
        return;
      }
      final List items = jsonDecode(jsonMatch.group(0)!);
      generatedTasks = items.map((item) {
        final timeParts = (item['time'] as String? ?? '09:00').split(':');
        final hour = int.tryParse(timeParts[0]) ?? 9;
        final minute = timeParts.length > 1 ? (int.tryParse(timeParts[1]) ?? 0) : 0;
        return PlannedTask(
          title: item['title'] ?? 'Untitled',
          dueDate: DateTime(date.year, date.month, date.day, hour, minute),
          priority: item['priority'] ?? 'medium',
          notes: item['notes'] ?? '',
        );
      }).toList();
    } catch (_) {
      errorMessage = 'Failed to parse AI response. Try again.';
    }
  }

  void _parseWeekTasks(String raw, DateTime startDate) {
    try {
      final jsonMatch = RegExp(r'\[.*\]', dotAll: true).firstMatch(raw);
      if (jsonMatch == null) {
        errorMessage = 'AI returned an unexpected format. Try again.';
        return;
      }
      final List items = jsonDecode(jsonMatch.group(0)!);
      generatedTasks = items.map((item) {
        final dateStr = item['date'] as String? ??
            DateFormat('yyyy-MM-dd').format(startDate);
        final parsed = DateTime.tryParse(dateStr) ?? startDate;
        final timeParts = (item['time'] as String? ?? '09:00').split(':');
        final hour = int.tryParse(timeParts[0]) ?? 9;
        final minute = timeParts.length > 1 ? (int.tryParse(timeParts[1]) ?? 0) : 0;
        return PlannedTask(
          title: item['title'] ?? 'Untitled',
          dueDate: DateTime(parsed.year, parsed.month, parsed.day, hour, minute),
          priority: item['priority'] ?? 'medium',
          notes: item['notes'] ?? '',
        );
      }).toList();
      // Sort by date/time
      generatedTasks.sort((a, b) => a.dueDate.compareTo(b.dueDate));
    } catch (_) {
      errorMessage = 'Failed to parse AI response. Try again.';
    }
  }

  /* ══════════════════════════════════════════════════════════════════
     EDIT A PLANNED TASK
     ══════════════════════════════════════════════════════════════════ */

  void updateTask(int index, PlannedTask updated) {
    if (index >= 0 && index < generatedTasks.length) {
      generatedTasks[index] = updated;
      notifyListeners();
    }
  }

  void removeTask(int index) {
    if (index >= 0 && index < generatedTasks.length) {
      generatedTasks.removeAt(index);
      notifyListeners();
    }
  }

  /* ══════════════════════════════════════════════════════════════════
     CONFIRM & UPLOAD ALL TASKS TO BACKEND
     ══════════════════════════════════════════════════════════════════ */

  Future<bool> confirmAndUpload() async {
    if (generatedTasks.isEmpty || _defaultListId == null) return false;

    isUploading = true;
    notifyListeners();

    final token = await SessionManager.getToken();
    final userId = await SessionManager.getUserId();
    if (token == null || userId == null) {
      isUploading = false;
      notifyListeners();
      return false;
    }

    int successCount = 0;
    for (final task in generatedTasks) {
      final payload = {
        'userId': userId,
        'taskListId': _defaultListId,
        'title': task.title,
        'notes': task.notes,
        'priority': task.priority,
        'dueDate': task.dueDate.toUtc().toIso8601String(),
        'status': 'pending',
        'isArchived': false,
        'reminder': {'enabled': false},
        'repeat': null,
      };

      try {
        final res = await http.post(
          Uri.parse('$_backendUrl/api/task'),
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer $token',
          },
          body: jsonEncode(payload),
        );
        if (res.statusCode == 200 || res.statusCode == 201) successCount++;
      } catch (_) {}
    }

    isUploading = false;
    final allOk = successCount == generatedTasks.length;
    if (allOk) generatedTasks.clear();
    notifyListeners();
    return allOk;
  }

  void clearPlan() {
    generatedTasks.clear();
    errorMessage = null;
    notifyListeners();
  }
}
